# Generated by Django 2.2.3 on 2019-08-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190815_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
