# Generated by Django 2.2.3 on 2019-08-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_comment_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.FilePathField(null=True),
        ),
    ]
