# Generated by Django 2.2.3 on 2020-10-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
        migrations.AddField(
            model_name='student',
            name='dadname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
